#####使用参数配置连接MongoDB
##服务器主机
#spring.data.mongodb.host=localhost
##数据库名称
#spring.data.mongodb.database=test
##服务器端口
#spring.data.mongodb.port=27017
###服务器用户名
##spring.data.mongodb.username=
###服务器密码
##spring.data.mongodb.password=
##要使用的FieldNamingStrategy的完全限定名称（有四种命名策略）
#spring.data.mongodb.field-naming-strategy=
##要启用的Mongo存储库的类型。
#spring.data.mongodb.repositories.type=auto
#
######使用Uri连接MongoDB
##spring.data.mongodb.uri=
spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017
